services:
  web:
    build: .
    container_name: library_web
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    entrypoint: ["/app/entrypoint.sh"]
    command: ["flask", "run", "--host=0.0.0.0"]
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - POWER_AUTOMATE_WEBHOOK_URL=https://prod-07.japaneast.logic.azure.com:443/workflows/eed1da13369f40fa96f10d2be52b5c14/triggers/manual/paths/invoke?api-version=2016-06-01
      - DEV_DATABASE_URL=mysql+pymysql://root:password@db/library_dev
      - TEST_DATABASE_URL=mysql+pymysql://root:password@db/library_test
      - DATABASE_URL=mysql+pymysql://root:password@db/library
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: library_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=library_dev
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
