services:
  web:
    build: .
    container_name: library_web
    ports:
      - "80:5000"
    volumes:
      - .:/app
    command: ["flask", "run", "--host=0.0.0.0"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: library_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=library_dev
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    name: db-data