"""Remove unique constraint from category1

Revision ID: 2a5d95b0bd03
Revises: ae47dbc5d010
Create Date: 2025-06-30 02:00:12.744503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5d95b0bd03'
down_revision = 'ae47dbc5d010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_location_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_location_mapping_category1'))
        batch_op.create_index(batch_op.f('ix_category_location_mapping_category1'), ['category1'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_location_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_location_mapping_category1'))
        batch_op.create_index(batch_op.f('ix_category_location_mapping_category1'), ['category1'], unique=True)

    # ### end Alembic commands ###
