"""Add status columns to Book and Reservation models

Revision ID: 73f95bb25112
Revises: a5cfeda2f864
Create Date: 2025-03-06 10:36:42.201002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f95bb25112'
down_revision = 'a5cfeda2f864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
