"""Add loan limits, extensions, and new tables

Revision ID: ae47dbc5d010
Revises: 60fbbc79acb2
Create Date: 2025-06-26 02:08:04.944097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae47dbc5d010'
down_revision = '60fbbc79acb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_location_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category1', sa.String(length=50), nullable=False),
    sa.Column('default_location', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category_location_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_location_mapping_category1'), ['category1'], unique=True)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_books_book_number'), ['book_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_books_registration_date'), ['registration_date'], unique=False)

    with op.batch_alter_table('loan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('extended_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_loan_limit', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('max_loan_limit')

    with op.batch_alter_table('loan_history', schema=None) as batch_op:
        batch_op.drop_column('extended_date')
        batch_op.drop_column('extension_count')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_registration_date'))
        batch_op.drop_index(batch_op.f('ix_books_book_number'))
        batch_op.drop_column('registration_date')
        batch_op.drop_column('book_number')

    op.drop_table('book_images')
    op.drop_table('announcements')
    with op.batch_alter_table('category_location_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_location_mapping_category1'))

    op.drop_table('category_location_mapping')
    # ### end Alembic commands ###
